export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { ClientProviders } from '@/providers/ClientProviders'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  )
}
