export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { ClientProviders } from '@/providers/ClientProviders'
import '@/styles/globals.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  )
}
