export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { ClientProviders } from '@/providers/ClientProviders'
import '@/styles/globals.css'

// Hunter Demand-Side: Environment validation (server-side only)
if (typeof window === 'undefined') {
  // Only run on server
  try {
    const { logEnvValidation } = require('@/lib/hunter/env-validation');
    logEnvValidation();
  } catch (error) {
    console.error('Failed to validate Hunter environment:', error);
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  )
}
