#!/usr/bin/env node

/**
 * Script to create a test user in Supabase for integration testing
 * 
 * Usage:
 *   node scripts/create-test-user.ts
 * 
 * This script:
 * 1. Creates a new test user in Supabase Auth
 * 2. Generates a valid JWT token for the user
 * 3. Outputs the TEST_USER_ID and TEST_JWT_TOKEN to add to .env.test
 */

import { createClient } from '@supabase/supabase-js';
import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';

// Read .env.test file manually
const envTestPath = path.resolve(process.cwd(), '.env.test');
const envContent = fs.readFileSync(envTestPath, 'utf-8');

// Parse environment variables
const envVars: Record<string, string> = {};
envContent.split('\n').forEach(line => {
  const trimmed = line.trim();
  if (trimmed && !trimmed.startsWith('#')) {
    const [key, ...valueParts] = trimmed.split('=');
    const value = valueParts.join('=').replace(/^["']|["']$/g, '');
    if (key && value) {
      envVars[key] = value;
    }
  }
});

const SUPABASE_URL = envVars.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = envVars.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error('❌ Missing environment variables:');
  console.error('   - NEXT_PUBLIC_SUPABASE_URL');
  console.error('   - SUPABASE_SERVICE_ROLE_KEY');
  console.error('\nMake sure these are set in your .env.test file');
  process.exit(1);
}

async function createTestUser() {
  try {
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    // Generate a unique test user email
    const timestamp = Date.now();
    const testEmail = `test-${timestamp}@example.com`;
    const testPassword = crypto.randomBytes(16).toString('hex');

    console.log(`\n📝 Creating test user: ${testEmail}`);

    // Create user via admin API
    const { data, error } = await supabase.auth.admin.createUser({
      email: testEmail,
      password: testPassword,
      email_confirm: true,
    });

    if (error) {
      console.error('❌ Error creating user:', error.message);
      process.exit(1);
    }

    const userId = data.user.id;
    console.log(`✅ Test user created successfully`);
    console.log(`\n📋 User Details:`);
    console.log(`   User ID: ${userId}`);
    console.log(`   Email: ${testEmail}`);
    console.log(`   Password: ${testPassword}`);

    // Note: The Supabase admin API doesn't provide a direct way to generate JWT tokens
    // The token needs to be generated by signing in with the user credentials
    // or by using the Supabase dashboard
    console.log(`\n⚠️  JWT Token Generation:`);
    console.log(`   The test user has been created successfully.`);
    console.log(`   To generate a JWT token, you have two options:`);
    console.log(`\n   Option 1: Use Supabase Dashboard`);
    console.log(`   - Go to: https://app.supabase.com/project/rebeznxivaxgserswhbn/auth/users`);
    console.log(`   - Find user: ${testEmail}`);
    console.log(`   - Click the user and copy the JWT token`);
    console.log(`\n   Option 2: Sign in with the user credentials`);
    console.log(`   - Use the email and password above to sign in`);
    console.log(`   - Copy the access_token from the session`);

    console.log(`\n📌 Add to your .env.test file:`);
    console.log(`\n   TEST_USER_ID=${userId}`);
    console.log(`   TEST_JWT_TOKEN=<get-from-dashboard-or-sign-in>`);
    console.log(`\n✨ Next steps:`);
    console.log(`   1. Generate JWT token using one of the options above`);
    console.log(`   2. Update .env.test with TEST_JWT_TOKEN`);
    console.log(`   3. Run integration tests:`);
    console.log(`      npm test -- src/__tests__/integration/edge-functions.test.ts --run\n`);

  } catch (error) {
    console.error('❌ Unexpected error:', error);
    process.exit(1);
  }
}

createTestUser();
